### ISSUE TITLE
Simulator nodes incompatible with gossip-nodes

### ISSUE THREAD

**Issue by svspire** [emotiq/emotiq#341] opened 2018-07-20 17:21 UTC
The simulator is using nodes that cannot work with the gossip system. Should we change the simulator to use gossip-compatible nodes, or blow off the simulator entirely and start testing using only real nodes?

Eugene's demo-network may have made the simulator obsolete now.

**Comment by easye** [comment] 2018-07-21 05:52
I don't understand "using nodes that cannot work with the gossip system".  What do you mean by the gossip system: the network transport, or the topological graph of nodes? 

When you refer to "Eugene's demo-network" what do you mean?  

Can you please explain what the problem is in more detail?

**Comment by dbmcclain** [comment] 2018-07-21 06:05
I didn’t make that statement, Shannon did. The simulator code runs fine, but as I understand it, we bypas actuall calls to the Gossip layer.

- DM

**Comment by svspire** [comment] 2018-07-21 06:15
> I don't understand "using nodes that cannot work with the gossip system". What do you mean by the gossip system: the network transport, or the topological graph of nodes?

I was slightly wrong before. I thought the simulator created a different class of nodes than gossip/Cosi needed. That's not correct; it creates gossip/Cosi nodes. However, it uses `make-instance` to create them, when it should be using `gossip:make-node` to create them. The latter ensures that nodes get registered in the `gossip::*nodes*` database and get initialized properly.

**Comment by svspire** [comment] 2018-07-21 06:16
> When you refer to "Eugene's demo-network" what do you mean?

See directory emotiq/demo-network

**Comment by easye** [comment] 2018-07-30 12:35
This can be fixed by merging `dev-eu` or `dev-us` which have removed the simulator in favor of running actual full gossip/cosi nodes in the local process to the point that they can sustain a chain. 

Blocked by auto-configuration issues https://github.com/emotiq/emotiq/issues/388

**Comment by easye** [comment] 2018-07-31 12:35
The gossip/cosi integration for single process multi-node hould be working with #389

**Comment by easye** [comment] 2018-07-31 13:37
Fixed with #389

**Closed as completed by easye** 2018-07-31 13:37 UTC
Labels: bug
